FROM node:19
WORKDIR /usr/src/app


COPY ./src/package*.json ./

RUN npm install
RUN chmod 777 -R node_modules

#test
RUN touch index.txt
RUN chmod 777 index.txt
#end_test

# RUN npm ci --only=production

COPY ./src .

EXPOSE 8080
CMD [ "node", "index.js" ]